### ISSUE TITLE
Plugin deprecated in SonarQube Marketplace

### ISSUE THREAD

**Issue by ganncamp** [SonarQubeCommunity/sonar-fxcop#11]
I wanted to let you know that this plugin has been removed from the SonarQube Marketplace and listed as [Deprecated](https://docs.sonarqube.org/display/PLUG/Deprecated+Plugins). Our analysis shows that it no longer works with the [SonarQube Scanner for MSBuild v4.0](https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/4.0.0.821)

For users 
* using v1.0 of the FxCop plugin, the builds will start failing with a Java exception.
* using a newer version of the FxCop plugin, the builds will not fail but the FxCop analysis will not be run -> impact on the issues reported in SonarQube.

**Comment by DanielHWe** [comment]
Hi,

thanks for the information, my last test was with Version 3 of the MSBuild Scanner, I was not aware that there was a new Version in December.

I will check and let you know when it was fixed.

Best,
Daniel

Von: G. Ann Campbell [mailto:notifications@github.com]
Gesendet: Tuesday, January 2, 2018 6:42 PM
An: DanielHWe/sonar-fxcop <sonar-fxcop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [DanielHWe/sonar-fxcop] Plugin deprecated in SonarQube Marketplace (#11)


I wanted to let you know that this plugin has been removed from the SonarQube Marketplace and listed as Deprecated<https://docs.sonarqube.org/display/PLUG/Deprecated+Plugins>. Our analysis shows that it no longer works with the SonarQube Scanner for MSBuild v4.0<https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/4.0.0.821>

For users

  *   using v1.0 of the FxCop plugin, the builds will start failing with a Java exception.
  *   using a newer version of the FxCop plugin, the builds will not fail but the FxCop analysis will not be run -> impact on the issues reported in SonarQube.

**Comment by DanielHWe** [comment]
With Version 1.2 of the Plugin the Analyse works, there are only some additional Parameters that must be set. I added the Information to the readme.md https://github.com/DanielHWe/sonar-fxcop/blob/master/README.md and will request Version 1.2 to be the official one.

**Comment by DanielHWe** [comment]
With 1.3 it is fixed. Please see readme for settings that must be used.

**Comment by PulsarFX** [comment]
The plugin is still listed as deprecated on https://docs.sonarqube.org/display/PLUG/Deprecated+Plugins
is this expected? 
Can/should this plugin be replaced with roslyn analyzers? see https://jira.sonarsource.com/browse/SONARMSBRU-338 : "... Moreover all the valuable FXCop rules have been rewritten and are now available out-of-the-box in SonarC#."

**Comment by DanielHWe** [comment]
I asked this in December 2016 to the sonar qube community. Answer was:
"[...]At the same time, we understand that many of our users still rely on FxCop, therefore, we extracted the functionality into a dedicated community plugin.

For a long time, Microsoft is planning to move FxCop onto Roslyn. When this work is done, you'll be able to use the SonarQube Roslyn SDK to generate a SonarQube plugin from FxCop. At the same time, as we realize that we can't wait for MS to do this work, we started analyzing what is our coverage over FxCop rules, and we'll work on lowering the size of the gap between the two products.
[...]"

See: https://groups.google.com/forum/#!searchin/sonarqube/C$23$20Code$20analyses$20rules$20from$20VS$20vs.$20Sonar$20Plugin|sort:date/sonarqube/6ZTYeyRzEno/jTqsrUqDBwAJ

May be you should ask the sonar qumunity for an update.
