### ISSUE TITLE
Define scan properties in command line

### ISSUE THREAD

**Issue by pramod84** [SonarQubeCommunity/sonar-fxcop#26]
Getting below error while running SonarQube.Scanner.MSBuild.exe end

ERROR: Path '$(FinalOutDir)bin/' found in output path, is not supported. Please define scan properties in command line or SonarQube.Analysis.xml.

I am using   1.4.2_SNAPSHOT2 version as i was facing issue with 1.4.1

WARNING: WARN: No output type found for 'xxxxx.csproj'.
WARNING: WARN: Ignore 'xxxxx.csproj' due to parsing error

**Comment by pramod84** [comment]
I am using below line during the begin step

SonarQube.Scanner.MSBuild.exe begin /n:"SV1.0" /v:"V1.0" /k:"DSV16" /d:"sonar.cs.fxcop.slnFile=xxx.sln" /d:"sonar.cs.fxcop.fxCopCmdPath=C:/Program Files (x86)/Microsoft Visual Studio 14.0/Team Tools/Static Analysis Tools/FxCop/FxCopCmd.exe" /d:"sonar.cs.fxcop.directory=D:/Binaries/Release/x64"

**Comment by pramod84** [comment]
I am actually migrating our SonarQube from 5.6 LTS to 6.7  LTS 
Earlier i was using sonar-fxcop-plugin-1.1 with sonar-csharp-plugin-5.11.0.1761.jar and everything was working fine.
$(FinalOutDir mentione aboce is  mentioned as  <OutputPath>$(FinalOutDir)bin\</OutputPath> in our csproj

**Comment by DanielHWe** [comment]
Due to braking changes in QonarQube 6.7 LTS you need to change your settings (Path in *.csproj), like described in the error message:

ERROR: Path '$(FinalOutDir)bin/' found in output path, is not supported. Please define scan properties in command line or SonarQube.Analysis.xml.

$(FinalOutDir) can not be resolved in the plugin

**Comment by pramod84** [comment]
can we define variables in scan properties in command line or SonarQube.Analysis.xml, if so how can we define the same
Is it that variables are not supported here.

We are not having much control on csproj or solution as Configuration managers and we cannot request the same as this codes are owned at different sites.

One more thing is i have downgraded the sonar plugins 
sonar-fxcop-plugin-1.1 with sonar-csharp-plugin-5.11.0.1761.jar with SonarQube 6.7 LTS and it works fine.
