### ISSUE TITLE
the report do not find Fxcop Rules in sonarqube

### ISSUE THREAD

**Issue by 123caner123** [SonarQubeCommunity/sonar-fxcop#38]
Hi,
I import fxcop rules in sonarqube .Also I activated fxcop rules  in Quality Profiles.But the report does not show any finding fxcop rules .How can I use fxcop rules in sonarqube.

![fxcop](https://user-images.githubusercontent.com/10937722/108611857-cb4cfe80-73f3-11eb-99fa-372a22045c57.png)

Thank You,
Best Regars.

**Comment by 123caner123** [comment]
I do not see fxcop rules here.But it need to find rules here.
![fxcoprule2](https://user-images.githubusercontent.com/10937722/108611923-837aa700-73f4-11eb-8541-e6e80ff0265b.png)

**Comment by DanielHWe** [comment]
You must run the plugin during the analyse phase otherwise you will not see the rules.
