### ISSUE TITLE
fxcop custom rule not coming for sonarqube

### ISSUE THREAD

**Issue by 123caner123** [SonarQubeCommunity/sonar-fxcop#39]
Hi,

I imported default fxcop rule.But Fxcop custom rule didnt import.

Default Rules.But I didnt see fxcop custom rules
![image](https://user-images.githubusercontent.com/10937722/108707695-78716500-7521-11eb-9e8b-bc3f1e22cbcc.png)
![image](https://user-images.githubusercontent.com/10937722/108707782-950d9d00-7521-11eb-8576-e92101310794.png)
There is no e-mail usage limitation custom rule in sonarqube.
![image](https://user-images.githubusercontent.com/10937722/108708166-1fee9780-7522-11eb-94e7-a2be09448521.png)

Thank You,
Best Regards

**Comment by DanielHWe** [comment]
The plugin does not support costum rules.
